name: Build Plugin Release

on:
  release:
    types: [ published ]

jobs:
  build:
    name:    Build Plugin Artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: echo Hello World